# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.rbruce.DataDemo.DataDemo
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  demo:
    description: all commands begin with demo
    usage: demo /<command> arguments
    permission: demo.*
permissions:
  demo.*:
    description: gives all permissions of the plugin commands
    default: true
    children:
      demo.message:
        description: gives permission to set the greeting message 
      demo.god:
        description: give the lighting bolt power
      demo.human:
        description: removes the lighting bolt power
